meta_product_name: "HireMe!"
meta_title: "HireMe! - The best Applicant Tracking System around"
meta_description: "Looking for a transparent hiring process? Check out our website!"
meta_image: "hireme.png" # should exist in `app/assets/images/`
